### ISSUE TITLE
Addition of a New User Record

### ISSUE THREAD

**Issue by cballou** [digitalocean/api-v2#1]
#### Add Ability to Create New User via API

As a service provider, POP.co is looking to utilize the automatic provisioning and creation of new Digital Ocean accounts on behalf of our users. Given that we already provide users with a custom domain, custom email, and DNS editing, it would make enormous sense for us to be able to offer the automated setup of VPS hosting for our users as well. We focus heavily on startups, entrepreneurs, and ideas people. We sponsor hackathons and our core audience is looking for full control over their domain.

Given our unique position, we have an extremely high interest in seeing the addition of `/user` added to the API. This endpoint would allow the creation of new Digital Ocean customers and return the API credentials necessary for managing the user account. In essence, it's Single-Sign On via OAUTH. 
#### Add CRUD Operations to New User

In addition to user creation, endpoints would be needed to perform get/update/delete. The `GET` call should include user settings such as referral codes. 
#### Add Referral Code Param to New User Endpoint

There should be a way to associate referral codes directly to new user creation via the API (https://www.digitalocean.com/referral-program/).
#### PROFIT!

There's a huge potential for monetization here by opening up these CRUD endpoints.
#### Contact Us

I'd love to discuss more; it's something we've spoken with your CTE John about recently. Email me directly at corey@pop.co for further clarification/ideas.

Regards,
Corey

**Comment by progrium** [comment]
This is great. Before I joined DO, I was pushing for the same thing. I think it's likely it'll make it in eventually. Thanks for validating this idea.

**Comment by raiyu** [comment]
Definitely something that we should look into but if we do provide this we would have to make sure that only certain trusted partners would have access otherwise would be used rampantly for abusive purposes.

**Comment by ForbiddenEra** [comment]
Hi,

I agree with OP but also with raiyu. The abuse factor is has a huge potential. Not to mention managing payments for every account might prove slightly complicated.

Honestly, if you really wanted to do this, you could. It's a bit of a pain in the a$$ but how do you think we automated things before JSON and AJAX?

**Comment by raiyu** [comment]
It's more about creating a partner program where it is only given out with limited access, not to everyone.

And in those cases we could put the onus on the partners to do the fraud screening. So if they have a customer that's been with them for X months, etc, and they want to create an account for them at DO that's certainly a different situation than simply opening this up publicly for any developer to use.

We'll treat this on a case by case basis, so if someone wants to reach out about a partnership for that we can look into it.

But otherwise this won't be making it to a public release due to the high probability of fraud and abuse.
