### ISSUE TITLE
Droplet Destroy API call is not reliable

### ISSUE THREAD

**Issue by max-at-mazebolt** [digitalocean/api-v2#104]
The Destroy call should only fail if the API is down or unreachable for the client. 

Right now the call can return an "ERROR" status and message, which client has nothing to do about.
Which is the same as saying "Ha-Ha, we won't destroy it.".
This issue becomes very relevant during automated bulk create/destroy operations.

Consider the next example:
1) We request 1000 droplets;
2) Only 200 are created successfully within justified timeout. Mean status is Active and passsed our own health checks.
3) So we issue destroy command to the rest 800 droplets in order to be sure we are left with only 200 good droplets.

By now there is no issue.

4) destroy command fails - with or without status reported - to us does not matter, because we can not do anything about it. We may only assume you took care of them.

And here the problem begins...

5) we request new 800, because we need it for the work to be done, and let's suppose they were created successfully.

Thus, by now we have 1000 working droplets + 800 "to be destroyed".

6) if those "to be destroyed" droplets come up later (1-2 hours like it happen to us recently), they will cause an overhead on your side + overhead on our side, with a very good potential of failing the work of the "working" droplets.

The above scenario is a real situation that happend on Nov 04, 2014 around 17:00 UTC.
We were launching 72 droplets in 3 european regions. At the fist iteration all of them hanged in New state for a couple of hours, API kept responding with "There is already an event scheduled for the droplet" for all destroy requests.
After a while, the system got back to a normal functioning and we were able to create 72 droplets successfully, but right after (or during) that another 52 droplets from the "to be destroyed" group came up...

There is a support ticket #435123 with more details on the issue.

We strongly believe, that the destroy operation should be the most reliable call in the API, or at least support "force" flag that will make it like that. Without it, automated work with Digital Ocean cloud is not reliable.

**Comment by phillbaker** [comment]
@max-at-mazebolt thanks for opening this issue. 

A few thoughts here, about the API usage:
- It looks like the creates that failed were due to an underlying issue that has now been resolved, which should reduce some of these issues going forward.
- In general, there’s no need to issue destroys for the creates that didn’t succeed, i.e. transition from "new" to "active". You should probably ensure that the create succeeds before issuing a destroy (or any action) for it.
- If the call to destroy fails (ie a non-2xx response), then a destroy could not be scheduled, and you could attempt to re-try scheduling the destroy or resolving the error until the status is appropriate.

For the force option on destroy, we'll definitely take that into consideration, however, it would likely entail a "cancel" functionality to cancel running events which we aren't going to implement immediately. For the mean time, opening a support ticket is the best option.
