### ISSUE TITLE
user_data in response to list/retrieve Droplet(s)

### ISSUE THREAD

**Issue by kontrafiktion** [digitalocean/api-v2#121]
The API to create a Droplets contains an attribute user_data, but when retrieving information about the Droplet, the response does not contain the value.

This is (i) inconsistent and (ii) could be used to "tag" Droplets, so that servers with the same tag could be handled as a "group"

**Comment by macb** [comment]
This is by design. Droplet `user_data` is only stored local to that droplet's server with the only intention that it made available to the droplet itself.

There is already a user voice for tagging droplets [here](https://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/2712160-group-servers). Feel free to contribute your support for that feature there.

Does that answer your question?

**Comment by kontrafiktion** [comment]
Yes, it answers my question. Thanks for the incredible fast reply.

Even if this is by design, I consider it an inconsistency. I think I can
retrieve every parameter that was used to create a Droplet, but not the
user_data.

Just checked that I already voted for
https://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/2712160-group-servers
some time ago

Thanks
