### ISSUE TITLE
Add tags on droplet creation

### ISSUE THREAD

**Issue by ashleyhindle** [digitalocean/api-v2#148]
I'd like to be able to add tags on droplet creation.  If the tags don't exist, it should add the tag and attach it to the droplet resource

**Comment by cubiclesoft** [comment]
I noticed this myself recently.  Since tags are a new addition to the v2 API and the initial release _barely_ supports Droplets, I suspect a few more roll outs will naturally deal with this and other issues related to tags.  Tagging is an extremely limited feature at the moment - it feels like they are gathering feedback on the current tagging bits from their larger users (i.e. not you or me) before deciding on any particular direction.

**Comment by andrewsomething** [comment]
The ability to add tags to a Droplet when creating was added to the API. See here for more info:

https://developers.digitalocean.com/documentation/changelog/api-v2/tagging-in-droplet-create/
