### ISSUE TITLE
More API endpoints for security with managed database clusters?!?

### ISSUE THREAD

**Issue by ghost** [digitalocean/api-v2#178]
I noticed there is a lack of API endpoints to modify security setting amongst DigitalOcean managed databases clusters, like `Trusted Sources`. Is this feature on the API roadmap, or at least being discussed internally?

**Comment by mmichealjroberts** [comment]
The ability to be able to edit the `Trusted Sources` for a managed database cluster would be essential for our currently automated deployment strategy. Could someone please update on the status of adding more managed database endpoints to the API?

**Comment by nylen** [comment]
Currently, fully automated provisioning of new droplets that need to access a DigitalOcean managed database is not possible due to this issue.

For `terraform`, the next step after DigitalOcean can add this API endpoint is described here: https://github.com/terraform-providers/terraform-provider-digitalocean/issues/223

**Comment by andrewsomething** [comment]
A new endpoint is now available for managing the inbound sources for database clusters. For more information, see the API changelog entry:

https://developers.digitalocean.com/documentation/changelog/api-v2/managed-databases-firewall-and-sql-mode-management/
