### ISSUE TITLE
Droplet is still active after shutdown completes

### ISSUE THREAD

**Issue by changhiskhan** [digitalocean/api-v2#79]
I couldn't find more descriptions of expected behavior in the docs but I created a droplet, called shutdown. I confirmed that the action was completed but status is still shown as "Active".

**Comment by macb** [comment]
@changhiskhan I'd be happy to take a look, could you email me the droplet ID? mac@digitalocean.com

**Comment by changhiskhan** [comment]
email sent. thx

**Comment by macb** [comment]
Thanks @changhiskhan. I took a look and the issue was not related to the API. The action was issued, took place, completed with success, however the droplet did not shutdown. 

The droplet `shutdown` action is a best effort attempt, as hung processes or something else could prevent `shutdown`. `power_off` is guaranteed to succeed, however it's dangerous and can lead to corrupted data since it is essentially pulling the plug.

**Comment by changhiskhan** [comment]
thanks for looking into it.
