### ISSUE TITLE
When transferring an image, is it a move or a copy?

### ISSUE THREAD

**Issue by KirkMunro** [digitalocean/api-v2#87]
I was just trying out the transfer action to transfer an image from one region to another.  The end result is that my image (a snapshot) is now in two regions.  That seems to indicate that "transfer" is actually "copy".  Is this the intended way for transfer to function, or a bug?  Does transfer function the same way for backup images as it does for snapshot images?  If this is the expected behaviour, will customers be billed for each region an image is located in?  Is there a way to remove a snapshot or a backup from a region once it is copied to another?  From what I have seen, the current documentation does not clearly describe transfer and as a result there are a few unanswered questions that could use some clarification.

Thanks!

**Comment by brookemckim** [comment]
Hi Kirk,

An image transfer is a copy of the image. The language is a bit confusing, but is the term we have been using since the beginning so our customers have come to expect it. Here is a [link](https://www.digitalocean.com/community/tutorials/how-to-migrate-digitalocean-snapshots-between-regions) to our official community article on the subject

We currently do not charge for snapshots and backups transferred to other regions.

Going to close this issue as it doesn't pertain to the API itself. If you have any further questions, for the fastest response, send an email to support@digitalocean.com.

Thanks!
